FROM public.ecr.aws/lambda/python:3.10

# Set environment variables
ENV PYTHONUNBUFFERED=1 \
    PYTHONPATH=/var/task \
    PIP_NO_CACHE_DIR=1

# Install common dependencies
COPY requirements.txt ${LAMBDA_TASK_ROOT}/
RUN pip install --upgrade pip && \
    pip install -r ${LAMBDA_TASK_ROOT}/requirements.txt

# Copy common library files
COPY agents/common ${LAMBDA_TASK_ROOT}/agents/common/

# Set working directory
WORKDIR ${LAMBDA_TASK_ROOT}

# Keep the container running
CMD ["app.lambda_handler"]